version: '3'
services:
    web:
        build: ./
        image: 'duydev-php-apache:7.1.18'
        ports:
            - '80'
        volumes:
            - './www:/var/www/html:rw'
            - './configs/php.ini:/usr/local/etc/php/php.ini:ro'
        links:
            - 'db'
        environment:
            VIRTUAL_HOST: 'amp.local'
            VIRTUAL_POST: '80'
    db:
        image: mariadb:10.1
        volumes:
            - mariadb:/var/lib/mysql
        environment:
            TZ: "Asia/Ho_Chi_Minh"
            MYSQL_ALLOW_EMPTY_PASSWORD: "no"
            MYSQL_ROOT_PASSWORD: "ROOT_PASSWORD"
            MYSQL_USER: 'DB_USER'
            MYSQL_PASSWORD: 'DB_PASS'
            MYSQL_DATABASE: 'DB_NAME'
volumes:
    mariadb:

networks:  
  default:
    external:
      name: nginx-net
